---
driver:
  name: vagrant
  customize:
    memory: 9000
    natdnshostresolver1: "on"
    natdnsproxy1: "on"
    nictype1: "virtio"
  network:
  - ["forwarded_port", {guest: 8181, host: 8333}]
  - ["forwarded_port", {guest: 8080, host: 8080}]
  - ["forwarded_port", {guest: 8088, host: 8088}]
  - ["forwarded_port", {guest: 8081, host: 8081}]
  - ["forwarded_port", {guest: 9088, host: 9088}]
  - ["forwarded_port", {guest: 4848, host: 4444}]
  - ["forwarded_port", {guest: 50070, host: 51070}]
  - ["forwarded_port", {guest: 50075, host: 51075}]
  - ["forwarded_port", {guest: 9200, host: 9200}]

provisioner:
  name: chef_solo

platforms:

#  - name: ubuntu-12.04
  - name: ubuntu-14.04
#  - name: centos-6.5

suites:
  - name: default
    run_list:
      - recipe[kagent::install]
      - recipe[ndb::install]
      - recipe[hops::install]
      - recipe[hopsworks::install]
      - recipe[elastic::install]
      - recipe[zeppelin::install]
      - recipe[spark::install]
      - recipe[flink::install]
#      - recipe[hiway::install]
      - recipe[ndb::mgmd]
      - recipe[ndb::ndbd]
      - recipe[ndb::mysqld]
      - recipe[hops::ndb]
      - recipe[hops::nn]
      - recipe[hops::dn]
      - recipe[hops::rm]
      - recipe[hops::nm]
      - recipe[hops::jhs]
      - recipe[hopsworks]
      - recipe[elastic::default]
#      - recipe[zeppelin::default]
      - recipe[spark::master]
      - recipe[spark::slave]
      - recipe[flink::jobmanager]
      - recipe[flink::taskmanager]
#      - recipe[hiway::hiway_client]
#      - recipe[hiway::hiway_worker]
#      - recipe[hiway::cuneiform_client]
#      - recipe[hiway::cuneiform_worker]
    attributes:
         # authorization:
         #    sudo:
         #      users: ['vagrant']
         #      passwordless: true
         #      include_sudoers_d: true
         # collectd:
         #    private_ips: ["10.0.2.15"]
         #    public_ips: ["10.0.2.15"]
         kagent:
            private_ips: ["10.0.2.15"]
            public_ips: ["10.0.2.15"]
         elastic:
            default:
                private_ips: ["10.0.2.15"]
                public_ips: ["10.0.2.15"]
            private_ips: ["10.0.2.15"]
            public_ips: ["10.0.2.15"]
         ndb:
            mgmd:
               private_ips: ["10.0.2.15"]
            ndbd:
               private_ips: ["10.0.2.15"]
            mysqld:
               private_ips: ["10.0.2.15"]
            memcached:
               private_ips: ["10.0.2.15"]
            private_ips: ["10.0.2.15"]
            public_ips: ["10.0.2.15"]
            enabled: "true"
         hops:
            nn:
               private_ips: ["10.0.2.15"]
            dn:
               private_ips: ["10.0.2.15"]
            rm:
               private_ips: ["10.0.2.15"]
            nm:
               private_ips: ["10.0.2.15"]
            jhs:
               private_ips: ["10.0.2.15"]
            use_hopsworks: "true"
         hdfs:
            user: glassfish
         hadoop:
            yarn: 
               user: glassfish
            mr: 
               user: glassfish
            nn:
               private_ips: ["10.0.2.15"]
            dn:
               private_ips: ["10.0.2.15"]
            rm:
               private_ips: ["10.0.2.15"]
            nm:
               private_ips: ["10.0.2.15"]
            jhs:
               private_ips: ["10.0.2.15"]
#            user_envs: "false"
         zeppelin:
            default:
               private_ips: ["10.0.2.15"]
            private_ips: ["10.0.2.15"]
            public_ips: ["10.0.2.15"]
         spark:
            user: glassfish
            slave:
               private_ips: ["10.0.2.15"]
            master:
               private_ips: ["10.0.2.15"]
            private_ips: ["10.0.2.15"]
         flink:
# This doesnt work
#            user: glassfish
            jobmanager:
               private_ips: ["10.0.2.15"]
            taskmanager:
               private_ips: ["10.0.2.15"]
         hopsworks:
            default:
               private_ips: ["10.0.2.15"]
            private_ips: ["10.0.2.15"]
            public_ips: ["10.0.2.15"]
            user_envs: "false"
         hiway:
            user: "hiway"
            private_ips: ["10.0.2.15"]
            public_ips: ["10.0.2.15"]
         private_ips: ["10.0.2.15"]
         public_ips: ["10.0.2.15"]
         vagrant: "true"
