---
driver:
  name: vagrant
  customize:
    memory: 9000
    natdnshostresolver1: "on"
    natdnsproxy1: "on"
    nictype1: "virtio"
  network:
  - ["forwarded_port", {guest: 8080, host: 8888}]
  - ["forwarded_port", {guest: 9191, host: 9999}]
  - ["forwarded_port", {guest: 4848, host: 4444}]
  - ["forwarded_port", {guest: 50070, host: 50070}]
  - ["forwarded_port", {guest: 50075, host: 50075}]

provisioner:
  name: chef_solo

platforms:

#  - name: ubuntu-12.04
  - name: ubuntu-14.04
#  - name: centos-6.5

suites:
  - name: default

suites:
  - name: default
    run_list:
      - recipe[kagent::install]
      - recipe[ndb::install]
      - recipe[hops::install]
      - recipe[hopsworks::install]
#      - recipe[collectd::install]
#      - recipe[kagent::default]
#      - recipe[collectd::server]
      - recipe[ndb::mgmd]
      - recipe[ndb::ndbd]
      - recipe[ndb::mysqld]
      - recipe[ndb::memcached]
      - recipe[hops::ndb]
      - recipe[hops::nn]
      - recipe[hops::dn]
      - recipe[hops::rm]
      - recipe[hops::nm]
      - recipe[hops::jhs]
      - recipe[hopsworks::default]
#      - recipe[collectd::mysqld]

    attributes:
#         download_url: "http://192.168.1.125/hops"
         collectd:
            private_ips: ["10.0.2.15"]
            public_ips: ["10.0.2.15"]
         kagent:
            private_ips: ["10.0.2.15"]
            public_ips: ["10.0.2.15"]
         kmon:
            private_ips: ["10.0.2.15"]
            public_ips: ["10.0.2.15"]
         hopsworks:
            admin:
#                password: "jimdowling"
            private_ips: ["10.0.2.15"]
            public_ips: ["10.0.2.15"]
         glassfish:
            cert:
#               password: "jamesdowling"
         ndb:
            mgmd:
               private_ips: ["10.0.2.15"]
            ndbd:
               private_ips: ["10.0.2.15"]
            mysqld:
               private_ips: ["10.0.2.15"]
            memcached:
               private_ips: ["10.0.2.15"]
            private_ips: ["10.0.2.15"]
            public_ips: ["10.0.2.15"]
            enabled: "true"
         hops:
            nn:
               private_ips: ["10.0.2.15"]
            dn:
               private_ips: ["10.0.2.15"]
            rm:
               private_ips: ["10.0.2.15"]
            nm:
               private_ips: ["10.0.2.15"]
            jhs:
               private_ips: ["10.0.2.15"]
         hadoop:
            nn:
               private_ips: ["10.0.2.15"]
            dn:
               private_ips: ["10.0.2.15"]
            rm:
               private_ips: ["10.0.2.15"]
            nm:
               private_ips: ["10.0.2.15"]
            jhs:
               private_ips: ["10.0.2.15"]
         private_ips: ["10.0.2.15"]
         public_ips: ["10.0.2.15"]
         vagrant: "enabled"
