---
driver:
  name: vagrant
  customize:
    memory: 10000
    natdnshostresolver1: "on"
    natdnsproxy1: "on"
    nictype1: "virtio"
  network:
  - ["forwarded_port", {guest: 3306, host: 9191}]
  - ["forwarded_port", {guest: 8080, host: 8080}]
  - ["forwarded_port", {guest: 8088, host: 8088}]
  - ["forwarded_port", {guest: 8081, host: 8081}]
  - ["forwarded_port", {guest: 9088, host: 9088}]
  - ["forwarded_port", {guest: 4848, host: 4444}]
  - ["forwarded_port", {guest: 50070, host: 51070}]
  - ["forwarded_port", {guest: 50075, host: 51075}]
  - ["forwarded_port", {guest: 9200, host: 9200}]

provisioner:
  name: chef_solo
  require_chef_omnibus: 12.4.3

platforms:

#  - name: ubuntu-12.04
  - name: ubuntu-14.04
#  - name: centos-6.5

suites:
  - name: default
    run_list:
      - recipe[kagent::install]
      - recipe[ndb::install]
      - recipe[hops::install]
      - recipe[elastic::install]
      - recipe[zeppelin::install]
      - recipe[spark::install]
      - recipe[flink::install]
      - recipe[charon::install]
      - recipe[hopsworks::install]
      - recipe[hiway::install]
      - recipe[ndb::mgmd]
      - recipe[ndb::ndbd]
      - recipe[ndb::mysqld]
      - recipe[hops::ndb]
      - recipe[hops::nn]
      - recipe[hops::dn]
      - recipe[hops::rm]
      - recipe[hops::nm]
      - recipe[hops::jhs]
      - recipe[elastic::default]
      - recipe[spark::master]
#      - recipe[flink::jobmanager]
#      - recipe[flink::taskmanager]
      - recipe[hopsworks]
      - recipe[spark::worker]
      - recipe[hiway::cuneiform_client]
      - recipe[hiway::hiway_client]
      - recipe[hiway::helloworld_client]
      - recipe[hiway::wordcount_client]
      - recipe[hiway::variantcall_client]
      - recipe[hiway::cuneiform_worker]
      - recipe[hiway::hiway_worker]
      - recipe[hiway::variantcall_worker]
      - recipe[charon::default]

    attributes:
         authorization:
            sudo:
              users: ['glassfish']
              passwordless: true
              include_sudoers_d: true
         kagent:
            private_ips: ["10.0.2.15"]
            enabled: true
         charon:
            default:
                private_ips: ["10.0.2.15"]
            user: glassfish
            group: hadoop
            user_email: jdowling@kth.se
            use_only_aws: true
            access_key: <%= ENV['AWS_ACCESS_KEY_ID'] %>
            secret_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
            conf_dir: "/srv/hadoop/etc/hadoop"
         elastic:
            default:
                private_ips: ["10.0.2.15"]
                public_ips: ["10.0.2.15"]
            private_ips: ["10.0.2.15"]
            public_ips: ["10.0.2.15"]
         ndb:
            mgmd:
               private_ips: ["10.0.2.15"]
            ndbd:
               private_ips: ["10.0.2.15"]
            mysqld:
               private_ips: ["10.0.2.15"]
            memcached:
               private_ips: ["10.0.2.15"]
            private_ips: ["10.0.2.15"]
            public_ips: ["10.0.2.15"]
            enabled: "true"
         hops:
            nn:
               private_ips: ["10.0.2.15"]
            dn:
               private_ips: ["10.0.2.15"]
            rm:
               private_ips: ["10.0.2.15"]
            nm:
               private_ips: ["10.0.2.15"]
            jhs:
               private_ips: ["10.0.2.15"]
            use_hopsworks: "true"
         hdfs:
            user: glassfish
         hadoop:
            yarn: 
               user: glassfish
               nm:
                   memory_mbs: '6656'
               vcores: '2'
            mr: 
               user: glassfish
            nn:
               private_ips: ["10.0.2.15"]
            dn:
               private_ips: ["10.0.2.15"]
            rm:
               private_ips: ["10.0.2.15"]
            nm:
               private_ips: ["10.0.2.15"]
            jhs:
               private_ips: ["10.0.2.15"]
#            user_envs: "false"
         zeppelin:
            default:
               private_ips: ["10.0.2.15"]
            private_ips: ["10.0.2.15"]
            public_ips: ["10.0.2.15"]
         spark:
            user: glassfish
            worker:
               private_ips: ["10.0.2.15"]
            master:
               private_ips: ["10.0.2.15"]
            private_ips: ["10.0.2.15"]
         flink:
# This doesnt work
#            user: glassfish
            jobmanager:
               private_ips: ["10.0.2.15"]
            taskmanager:
               private_ips: ["10.0.2.15"]
         hopsworks:
            default:
               private_ips: ["10.0.2.15"]
            private_ips: ["10.0.2.15"]
            public_ips: ["10.0.2.15"]
            user_envs: "false"
#         twofactor_auth: "true"
         hiway:
            user: "glassfish"
            private_ips: ["10.0.2.15"]
            public_ips: ["10.0.2.15"]
            am:
              memory_mb: '512'
              vcores: '1'
            worker:
              memory_mb: '3072'
              vcores: '1'
            hiway:
              hdfs
                 basedir: "/"
         private_ips: ["10.0.2.15"]
         public_ips: ["10.0.2.15"]
         vagrant: "true"
