---
driver:
  name: vagrant
  customize:
    memory: 10000
    natdnshostresolver1: "on"
    natdnsproxy1: "on"
    nictype1: "virtio"
  network:
  - ["forwarded_port", {guest: 3306, host: 3939}]
  - ["forwarded_port", {guest: 8080, host: 8080}]
  - ["forwarded_port", {guest: 8088, host: 8088}]
  - ["forwarded_port", {guest: 8181, host: 8181}]
  - ["forwarded_port", {guest: 9088, host: 9088}]
  - ["forwarded_port", {guest: 4848, host: 4444}]
  - ["forwarded_port", {guest: 50070, host: 51070}]
  - ["forwarded_port", {guest: 50075, host: 51075}]
  - ["forwarded_port", {guest: 9200, host: 9200}]

provisioner:
  name: chef_solo
  require_chef_omnibus: 12.4.3

platforms:

#  - name: ubuntu-15.04
  - name: ubuntu-14.04
#  - name: centos-7.0

suites:
  - name: default
    run_list:
       - recipe[kagent::install]
       - recipe[hopsworks::install]
       - recipe[ndb::install]
       - recipe[hops::install]
       - recipe[elastic::install]
       - recipe[zeppelin::install]
       - recipe[spark::install]
       - recipe[flink::install]
       - recipe[ndb::mgmd]
       - recipe[ndb::ndbd]
       - recipe[ndb::mysqld]
       - recipe[hops::ndb]
       - recipe[hops::nn]
       - recipe[hops::dn]
       - recipe[hops::rm]
       - recipe[hops::nm]
       - recipe[hops::jhs]
       - recipe[elastic::default]
       - recipe[spark::yarn]
       - recipe[hopsworks]

    attributes:
        # authorization:
        #    sudo:
        #      users: ['vagrant']
        #      passwordless: true
        #      include_sudoers_d: true
         kagent:
            private_ips: ["10.0.2.15"]
            enabled: true
            use_systemd: "true"
         elastic:
            default:
                private_ips: ["10.0.2.15"]
                public_ips: ["10.0.2.15"]
            private_ips: ["10.0.2.15"]
            public_ips: ["10.0.2.15"]
            use_systemd: "true"
         ndb:
            mgmd:
               private_ips: ["10.0.2.15"]
            ndbd:
               private_ips: ["10.0.2.15"]
            mysqld:
               private_ips: ["10.0.2.15"]
            memcached:
               private_ips: ["10.0.2.15"]
            private_ips: ["10.0.2.15"]
            public_ips: ["10.0.2.15"]
            enabled: "true"
            use_systemd: "true"
         hops:
            nn:
               private_ips: ["10.0.2.15"]
            dn:
               private_ips: ["10.0.2.15"]
            rm:
               private_ips: ["10.0.2.15"]
            nm:
               private_ips: ["10.0.2.15"]
            jhs:
               private_ips: ["10.0.2.15"]
            use_hopsworks: "true"
            use_systemd: "true"
         hdfs:
            user: glassfish
            conf_dir: "/srv/hadoop/etc/hadoop"
         hadoop:
            yarn: 
               user: glassfish
               nm:
                   memory_mbs: '6656'
               vcores: '2'
            mr: 
               user: glassfish
            nn:
               private_ips: ["10.0.2.15"]
            dn:
               private_ips: ["10.0.2.15"]
            rm:
               private_ips: ["10.0.2.15"]
            nm:
               private_ips: ["10.0.2.15"]
            jhs:
               private_ips: ["10.0.2.15"]
            use_systemd: "true"
         zeppelin:
            default:
               private_ips: ["10.0.2.15"]
            private_ips: ["10.0.2.15"]
            public_ips: ["10.0.2.15"]
         spark:
            user: glassfish
            worker:
               private_ips: ["10.0.2.15"]
            master:
               private_ips: ["10.0.2.15"]
            private_ips: ["10.0.2.15"]
         flink:
# This doesnt work
            user: glassfish
            jobmanager:
               private_ips: ["10.0.2.15"]
            taskmanager:
               private_ips: ["10.0.2.15"]
            use_systemd: "true"
         hopsworks:
            default:
               private_ips: ["10.0.2.15"]
            private_ips: ["10.0.2.15"]
            public_ips: ["10.0.2.15"]
            user_envs: "false"
            twofactor_auth: false
            use_systemd: "true"
         private_ips: ["10.0.2.15"]
         public_ips: ["10.0.2.15"]
         # glassfish:
         #      version: "4.1"
         #      package_url: "http://193.10.67.171/hops/glassfish-4.1.zip"
         #      domains: 
         #        domain1: 
         #          config: 
         #            port: 7070
         #            admin_port: 4848
         #            username: admin
         #            password: admin
         #            master_password: mykeystorepassword
         #            remote_access: true
         # java:
         #     install_flavor: oracle
         #     jdk_version: 7
         #     oracle:       
         #       accept_oracle_download_terms: "true"

